---
title: "rrs"
output:
  html_document:
    df_print: paged
  reference_docx: rss_style.docx
  code_folding: hide
  word_document: default
  pdf_document: default
  fig_width: 8 
fig_height: 4
---
```{r echo=FALSE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```


```{r libraries, echo=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(readxl)
library(DT)
library(plotly)
library(lubridate)
library(RcppRoll)
library(scales)
library(ggrepel)
```
```{r função "dados" importar e renomear variaveis}
# funcao para importar dados e renomear variaveis
dados = function(tg, depara){
  # carregar planilha com dados do Tesouro Gerencial (tg)
  df <- read_xlsx(tg)
  # carregar planilha com o de_para dos nomes dos atributos do Tesouro Gerencial para nomes mais amigáveis para as variáveis. Por exemplo, de(Unidade Orçamentária Código) para(uo_cod)
  tg2r <- read_xlsx(depara)
  # renomear as colunas da df fazendo o de_para
  colnames(df)<-tg2r$r_name
  return(df)
}
```


```{r negar %in%}
# https://www.r-bloggers.com/the-notin-operator/
'%!in%' <- Negate('%in%')
```

```{r}
rp <- dados("rp.xlsx","tg2r_rp.xlsx")%>% mutate(mes = paste0(ano,"-",mês,"-","01"))%>% 
  #  alterar NA por 0
  mutate_all(~replace(., is.na(.), 0))%>% mutate (a_pagar = rpp + rpnp)

rp <- rp %>% mutate (mes = ymd (mes))


rp_acumulado <- rp %>% group_by(mes) %>% summarise(saldo_a_pagar= sum(a_pagar))
 

rp <- rp %>% mutate (a_pagar = rpp + rpnp)%>%   mutate(acumulado = roll_sum(a_pagar,12, fill=NA, align="right"))

# rp <- rp %>% mutate(mes = paste0(ano,"-",mês,"-","01"))
# rp_acumulado <- rp_acumulado %>% mutate (mes = ymd (mes)) 
rp_acumulado <- rp %>% group_by(mes) %>% summarise(a_pagar= sum(a_pagar)) %>%   mutate(acumulado = roll_sum(a_pagar,12, fill=NA, align="right"))


ggplot(rp_acumulado,aes(x = (as.Date(mes)),y = acumulado) ) + 
  
  geom_line()+
  # plotar o point da UF selecionada
    # geom_label(label = rcl %>% filter (mes== max(mes)) %>% summarise(acumulado=acumulado))+
    # 
    geom_label_repel(data = rp_acumulado%>% filter (mes %in% c(max(mes))), aes(x=as.Date(mes), y=acumulado,label=paste0( prettyNum(round(acumulado/1000000000,0), big.mark = ".", decimal.mark = ","), " (",month(mes,label = TRUE) ,")")))+
 geom_point(data = rp_acumulado%>% filter (mes %in% c(max(mes))), aes(x=as.Date(mes), y=acumulado))+
 
  ggtitle(paste0("rp (posição: ",(month(max(as.Date(rp_acumulado$mes)), label=TRUE)), "/",(year(max(as.Date(rp_acumulado$mes)))),")" ))+
    theme_classic() +
    ylab("R$ bilhões") +
    xlab("") +
    theme(axis.text.x = element_text(size=8),
          axis.text.y = element_text(size=8),
          legend.position = "none")+ 
    scale_x_date(limits = c(as.Date ("2013-01-01"),as.Date(max(rp_acumulado$mes))) ,breaks=date_breaks("1 year"),
      labels=date_format( "%Y"))



 ggsave("rp.png", width = 24, height = 9, units = "cm",  dpi = 1200)

```



```{r}


rp <- dados("rp.xlsx","tg2r_rp.xlsx")%>% mutate(mes = paste0(ano,"-",mês,"-","01"))%>% mutate (a_pagar = rpp + rpnp)

rp <- rp %>% mutate (mes = ymd (mes))


rp_acumulado <- rp %>% group_by(mes) %>% summarise(saldo_a_pagar= sum(a_pagar))
 

rp <- rp %>% mutate (a_pagar = rpp + rpnp)%>%   mutate(acumulado = roll_sum(a_pagar,12, fill=NA, align="right"))

# rp <- rp %>% mutate(mes = paste0(ano,"-",mês,"-","01"))
# rp_acumulado <- rp_acumulado %>% mutate (mes = ymd (mes)) 
rp_acumulado <- rp %>% group_by(mes) %>% summarise(a_pagar= sum(a_pagar)) %>%   mutate(acumulado = roll_sum(a_pagar,12, fill=NA, align="right"))


ggplot(rp %>%  group_by(mes, grupo) %>% summarise(a_pagar=sum(a_pagar)),aes(x = (as.Date(mes)),y = a_pagar, fill = grupo) ) + 
  
  geom_col()+
  # plotar o point da UF selecionada
    # geom_label(label = rcl %>% filter (mes== max(mes)) %>% summarise(acumulado=acumulado))+
    # 
    geom_label_repel(data = rp%>% filter (mes %in% c(max(mes))), aes(x=as.Date(mes), y=a_pagar,label=paste0( prettyNum(round(a_pagar/1000000000,0), big.mark = ".", decimal.mark = ","), " (",month(mes,label = TRUE) ,")")))+
 # geom_point(data = rp%>% filter (mes %in% c(max(mes))), aes(x=as.Date(mes), y=a_pagar))+
 
  ggtitle(paste0("rp (posição: ",(month(max(as.Date(rp$mes)), label=TRUE)), "/",(year(max(as.Date(rp$mes)))),")" ))+
    theme_classic() +
    ylab("R$ bilhões") +
    xlab("") +
    theme(axis.text.x = element_text(size=8),
          axis.text.y = element_text(size=8),
          legend.position = "none")+ 
    scale_x_date(limits = c(as.Date ("2013-01-01"),as.Date(max(rp$mes))) ,breaks=date_breaks("1 year"),
      labels=date_format( "%Y"))



 ggsave("rp.png", width = 24, height = 9, units = "cm",  dpi = 1200)

```

```{r}
rp <- dados("rp.xlsx","tg2r_rp.xlsx")%>% mutate(mes = paste0(ano,"-",mês,"-","01"))%>% 
  #  alterar NA por 0
  mutate_all(~replace(., is.na(.), 0))%>% mutate (a_pagar = rpp + rpnp)

rp <- rp %>% mutate (mes = ymd (mes))


rp_acumulado <- rp %>% group_by(mes) %>% summarise(saldo_a_pagar= sum(a_pagar))
 

rp <- rp %>% mutate (a_pagar = rpp + rpnp)%>%   mutate(acumulado = roll_sum(a_pagar,12, fill=NA, align="right"))

# rp <- rp %>% mutate(mes = paste0(ano,"-",mês,"-","01"))
# rp_acumulado <- rp_acumulado %>% mutate (mes = ymd (mes)) 
rp_ne_ano <- rp %>% group_by( ne_ano)  %>% summarise(a_pagar= sum(a_pagar))


ggplot(rp_ne_ano,aes(  ne_ano, a_pagar), fill = ne_ano ) + 
  
  geom_col()+
  # plotar o point da UF selecionada
    # geom_label(label = rcl %>% filter (mes== max(mes)) %>% summarise(acumulado=acumulado))+
    # 
   
  ggtitle(paste0("rp (posição: ",(month(max(as.Date(rp$mes)), label=TRUE)), "/",(year(max(as.Date(rp$mes)))),")" ))+
    theme_classic() +
    ylab("R$ bilhões") +
    xlab("") +
    theme(axis.text.x = element_text(size=8),
          axis.text.y = element_text(size=8),
          legend.position = "none")+ scale_colour_brewer()



 ggsave("rp.png", width = 24, height = 9, units = "cm",  dpi = 1200)
```




```{r,fig.width = 10, fig.height= 4}
rcl <- read_excel("rcl_pbi.xlsx")

names(rcl)[6] <- "rcl_liquida_mes"

names(rcl)[1] <- "mes"

rcl <- rcl %>% mutate(acumulado = roll_sum(rcl_liquida_mes,12, fill=NA, align="right")/1000000)

rclLast <- rcl %>% # last trading day
 filter(mes== max(mes))

library(zoo)
mes_final <-  rcl%>% filter (mes == max(mes))

ggplot(rcl,aes(x = (as.Date(mes)),y = acumulado) ) + 
  
  geom_line()+
  # plotar o point da UF selecionada
    # geom_label(label = rcl %>% filter (mes== max(mes)) %>% summarise(acumulado=acumulado))+
    # 
    geom_label_repel(data = rcl%>% filter (mes %in% c(max(mes),"2020-03-01", "2020-12-01")), aes(x=as.Date(mes), y=acumulado,label=paste0( prettyNum(round(acumulado/1000,0), big.mark = ".", decimal.mark = ","), " (",month(mes,label = TRUE) ,")")))+
 geom_point(data = rcl%>% filter (mes %in% c(max(mes),"2020-03-01", "2020-12-01")), aes(x=as.Date(mes), y=acumulado))+
 
  ggtitle(paste0("Receita Corrente Líquida (posição: ",(month(max(as.Date(rcl$mes)), label=TRUE)), "/",(year(max(as.Date(rcl$mes)))),")" ))+
    theme_classic() +
    ylab("R$ bilhões") +
    xlab("") +
    theme(axis.text.x = element_text(size=8),
          axis.text.y = element_text(size=8),
          legend.position = "none")+ 
    scale_x_date(limits = c(as.Date ("2008-01-01"),as.Date(max(rcl$mes))) ,breaks=date_breaks("1 year"),
      labels=date_format( "%Y"))



 ggsave("rcl.png", width = 24, height = 9, units = "cm",  dpi = 1200)

# 
# names(rcl) <- c("item",teste)
# 
# rcl %>% filter(startsWith(item,"RECEITA")) %>% pivot_longer(cols = everything())
```

```{r}
previ <- read_excel("previ.xlsx")

names(previ)[1] <- "date"

previ <- previ %>% mutate (receita =rowSums( previ[,startsWith(names(previ),"Movimento R")]), despesa  =rowSums( previ[,startsWith(names(previ),"Movimento D")]), resultado = receita - despesa)

previ2 <- previ  %>% select(ends_with("Meses"))

datatable(previ)
# https://itsalocke.com/blog/understanding-rolling-calculations-in-r/
previ <- previ %>% mutate(acumulado = roll_sum(resultado,12, fill=NA, align="right")/1000000000)
```
```{r,fig.width = 8, fig.height= 4}
# https://itsalocke.com/blog/understanding-rolling-calculations-in-r/
previ_plot <- ggplot(previ , aes(x = (as.Date(date)),y = acumulado)) + 
  geom_line(aes( ))+
  ggtitle(paste0( "Resultado Previdenciário acumulado nos últimos 12 meses (posição: ",month(max(as.Date(previ$date))), "/",year(max(as.Date(previ$date))),")"))+
   geom_label_repel(data = previ%>% filter (date == max(date)), aes(x=as.Date(date), y=acumulado,label=paste( round(acumulado,0)))) +
    theme_classic() +
    ylab("R$ bilhões") +
    xlab("") +
    theme(axis.text.x = element_text(size=8),
          axis.text.y = element_text(size=8),
          legend.position = "none")+ 
    scale_x_date(breaks=date_breaks("1 year"),
      labels=date_format( "%Y"))

ggsave("previ.png", width = 30, height = 15, units = "cm",  dpi = 1200)
   # geom_smooth(method = "loess", color = "red") 
```



```{r}
educacao <- read_excel("educacao.xlsx")

# names(my_data)[1] <- "sepal_length"
# names(my_data)[2] <- "sepal_width"

educacao <- educacao %>% mutate (percentual = 100*executado/mínimo, mes = month(date, label = TRUE), ano = year(date))

educacao <- educacao %>% mutate(cores = if_else(percentual>100,"red","blue"))

p <- ggplot(educacao, aes(y=percentual, color = cores)) +
  # geom_jitter exclui a UF selecionada para evitar a apresentação de dois pontos para a mesma UF.
  # Caso contrário teríamos um ponto plotado pelo geom_jitter e outro plotado pelo geom_point
    geom_jitter( data = educacao %>% filter (ano != max(ano)), aes(x = mes, text=paste("ANO: ", ano)), alpha=0.2) +
  # plotar o point da UF selecionada
    geom_point(data = educacao %>% filter (ano == max(ano)), aes(x=mes, y=percentual,text=paste("ANO: ", ano)))+
  
  # plotar linha vermelha tracejada dividindo resultados bons (azul), ruins (vermelho). O argumento "corte" define a altura da linha.
    geom_hline(yintercept=100, colour = "red", linetype = "dashed") +
  # https://ggplot2.tidyverse.org/reference/geom_smooth.html
  # inherit.aes =FALSE para evitar duas linhas de tendência.
  # Caso contrário teríamos uma linha de tendência para a cada factor level (coluna cores).
  # Uma linha de tendência para os pontos de cor vermelha e outra linha de tendência para os pontos de cor azul  
    geom_smooth( method = "loess", inherit.aes =FALSE,aes(x=mes, y=percentual), color = "gray" )+
  # inherit.aes =FALSE para nao herdar aes do geoms anteriores. Caso contrário a linha teria duas cores
    geom_line(data = educacao %>% filter (ano == max(ano) ),  inherit.aes =TRUE, aes(x=month(as.Date(date)), y=percentual))+ 
  
   # definir informação dos eixos
    labs( x = "mês",
          y = "%")+ theme_classic()+ 
  # escala de cor. Os levels são definidos na coluna cores da df_limites.
    scale_color_manual(breaks = levels(educacao$cores),
                        values=c("red", "blue"))+
  ggtitle("Percentual mínimo de despesa com Educação")+
  # optei por esconder a legenda (showlegend = FALSE)
geom_text(data = educacao %>% filter (date == max(date)), aes(x=mes, y=percentual+3.5, label = ano))
# (p <- ggplotly(p))%>% layout(showlegend = FALSE)
p
```

```{r}
rp <- read_excel("rp.xlsx")
```



```{r}
saude <- read_excel("saude.xlsx")

names(saude)[1] <- "date"
names(saude)[2] <- "executado"
names(saude)[5] <- "minimo"

saude <- saude %>% mutate (percentual = 100*executado/minimo, mes = month(date, label = TRUE), ano = year(date))

saude <- saude %>% mutate(cores = if_else(percentual>100,"red","blue"))

```


```{r}
p <- ggplot(saude, aes(y=percentual, color = cores)) +
  # geom_jitter exclui a UF selecionada para evitar a apresentação de dois pontos para a mesma UF.
  # Caso contrário teríamos um ponto plotado pelo geom_jitter e outro plotado pelo geom_point
    geom_jitter( data = saude %>% filter (ano != max(ano)), aes(x = mes, text=paste("ANO: ", ano)), alpha=0.2) +
  # plotar o point da UF selecionada
    geom_point(data = saude %>% filter (ano == max(ano)), aes(x=mes, y=percentual,text=paste("ANO: ", ano)))+
  
  # plotar linha vermelha tracejada dividindo resultados bons (azul), ruins (vermelho). O argumento "corte" define a altura da linha.
    geom_hline(yintercept=100, colour = "red", linetype = "dashed") +
  # https://ggplot2.tidyverse.org/reference/geom_smooth.html
  # inherit.aes =FALSE para evitar duas linhas de tendência.
  # Caso contrário teríamos uma linha de tendência para a cada factor level (coluna cores).
  # Uma linha de tendência para os pontos de cor vermelha e outra linha de tendência para os pontos de cor azul  
    geom_smooth( method = "loess", inherit.aes =FALSE,aes(x=mes, y=percentual), color = "gray" )+
  # inherit.aes =FALSE para nao herdar aes do geoms anteriores. Caso contrário a linha teria duas cores
    geom_line(data = saude %>% filter (ano == max(ano) ),  inherit.aes =FALSE, aes(x=month(as.Date(date)), y=percentual))+ 
  
   # definir informação dos eixos
    labs( x = "mês",
          y = "%")+ theme_classic()+ 
  # escala de cor. Os levels são definidos na coluna cores da df_limites.
    scale_color_manual(breaks = levels(saude$cores),
                        values=c("red", "blue"))+
  ggtitle("Percentual mínimo de despesa com Saúde")+
  # optei por esconder a legenda (showlegend = FALSE)
geom_label_repel(data = saude %>% filter (date == max(date)), aes(x=mes, y=percentual+3.5, label = paste0(round(percentual,1),"%")))
# (p <- ggplotly(p))%>% layout(showlegend = FALSE)
p

ggsave("saude.png", width = 30, height = 15, units = "cm")
```

```{r}
p <- ggplot(saude, aes(y=percentual, color = cores)) +
  # geom_jitter exclui a UF selecionada para evitar a apresentação de dois pontos para a mesma UF.
  # Caso contrário teríamos um ponto plotado pelo geom_jitter e outro plotado pelo geom_point
    geom_jitter( data = saude %>% filter (ano != "2015"), aes(x = mes, text=paste("ANO: ", ano)), alpha=0.2) +
  # plotar o point da UF selecionada
    geom_point(data = saude %>% filter (ano == "2015"), aes(x=mes, y=percentual,text=paste("ANO: ", ano)), size = 2)+
  
  # plotar linha vermelha tracejada dividindo resultados bons (azul), ruins (vermelho). O argumento "corte" define a altura da linha.
    geom_hline(yintercept=100, colour = "red", linetype = "dashed") +
  # https://ggplot2.tidyverse.org/reference/geom_smooth.html
  # inherit.aes =FALSE para evitar duas linhas de tendência.
  # Caso contrário teríamos uma linha de tendência para a cada factor level (coluna cores).
  # Uma linha de tendência para os pontos de cor vermelha e outra linha de tendência para os pontos de cor azul  
    # geom_smooth( method = "loess", inherit.aes =FALSE,aes(x=mes, y=percentual), color = "gray" )+
  # inherit.aes =FALSE para nao herdar aes do geoms anteriores. Caso contrário a linha teria duas cores
    geom_line(data = saude %>% filter (ano == "2015" ),  inherit.aes =TRUE, aes(x=month(as.Date(date)), y=percentual),size = 1, color = "gray")+ 
  
   # definir informação dos eixos
    labs( x = "mês",
          y = "%")+ theme_classic()+ 
  # escala de cor. Os levels são definidos na coluna cores da df_limites.
    scale_color_manual(breaks = levels(saude$cores),
                        values=c("red", "blue"))+
  ggtitle("Percentual mínimo de despesa com Saúde")+
  # optei por esconder a legenda (showlegend = FALSE)
geom_text(data = saude %>% filter (date == max(date)), aes(x=mes, y=percentual+3.5, label = ano))
# (p <- ggplotly(p))%>% layout(showlegend = FALSE)
p
```




